### PR TITLE
Bugfix #3 #4 #5

### LINKED ISSUE #3: reset focused element on dimchange
if you change the dimension and the focuselmentindex in the new list is greater than the count, you can not use the keyboard to change the focus.
Please reset the focusedItem index to 0 on every dimensionlist change

### LINKED ISSUE #4: search in dimensionlist not working
you can jump to search an input something, but this has no effect on the dimensionlist

### LINKED ISSUE #5: dimensionlist property change
if you change the element of the dimenesion, you have to restart the browser to get the right dimensions in the list

### PR DESCRIPTION
**Pull request by thomashaenig**
Fixes #5 
Fixes #3 
Fixes #4 

### Status
```
[ ] Under development
[ ] Waiting for code review
[x] Waiting for merge

### Information
```
[ ] Contains breaking changes
[ ] Contains new API(s)
[x] Contains documentation
[ ] Contains test
```
### To-do list
```
[x] [Fix this thing]
[ ] [Fix another thing]
[ ] ...
```

### CODE REVIEW

File: src/lib/daVinci.js/src/utils/object.ts [hunk 1]
```diff
@@ -80,25 +82,30 @@ export class q2gListAdapter {
...
         this.obj.getDataPage(this.itemsPagingTop, this.itemsPagingHeight)
             .then((collection: Array<any>) => {
                 
                 if (!this._collection || !checkEqualityOfArrays(this._collection, collection)) {
-                    this._collection = collection;
-                }
 
-                
+                    let counter: number = 0;
+                    collection.forEach((x) => {
```
Comment (konne) [inline src/lib/daVinci.js/src/utils/object.ts]: please change after your free days :-)

Comment (konne) [inline src/lib/daVinci.js/src/utils/object.ts]: @thomashaenig see my comment
